name: Typo Reporter CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Run unit tests
        run: mvn -B -ntp -fae clean test
      - name: Run integration tests
        run: mvn -B -ntp -Dtest=noTest -DfailIfNoTests=false verify